!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node85
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 8586100969
 ip address 10.8.169.1/24
!
interface 8596100969
 ip address 10.8.191.2/24
!
interface 8574100969
 ip address 10.8.148.2/24
!
ip forwarding
!
!
line vty
!
