!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node80_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 8092100342
!
interface 8081100342
!
interface 8079100342
!
interface 8068100342
!
router ospf
 ospf router-id 10.8.0.80
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
