!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node80
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 8092100342
 ip address 10.8.160.1/24
!
interface 8081100342
 ip address 10.8.159.1/24
!
interface 8079100342
 ip address 10.8.157.2/24
!
interface 8068100342
 ip address 10.8.136.2/24
!
ip forwarding
!
!
line vty
!
