!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node32
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 324494397
 ip address 10.8.64.1/24
!
interface 323394397
 ip address 10.8.63.1/24
!
interface 323194397
 ip address 10.8.61.2/24
!
interface 322094397
 ip address 10.8.40.2/24
!
ip forwarding
!
!
line vty
!
