!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node95
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 9596102200
 ip address 10.8.189.1/24
!
interface 9594102200
 ip address 10.8.187.2/24
!
interface 9584102200
 ip address 10.8.168.2/24
!
ip forwarding
!
!
line vty
!
