!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node68_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 688098865
!
interface 686998865
!
interface 686798865
!
interface 685698865
!
router ospf
 ospf router-id 10.8.0.68
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
