!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node44
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 445695856
 ip address 10.8.88.1/24
!
interface 444595856
 ip address 10.8.87.1/24
!
interface 444395856
 ip address 10.8.85.2/24
!
interface 443295856
 ip address 10.8.64.2/24
!
ip forwarding
!
!
line vty
!
