!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node15
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 152692271
 ip address 10.8.30.1/24
!
interface 151692271
 ip address 10.8.29.1/24
!
interface 151492271
 ip address 10.8.27.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
