!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node79
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 7991100213
 ip address 10.8.158.1/24
!
interface 7980100213
 ip address 10.8.157.1/24
!
interface 7978100213
 ip address 10.8.155.2/24
!
interface 7967100213
 ip address 10.8.134.2/24
!
ip forwarding
!
!
line vty
!
