!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node87
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 8788101219
 ip address 10.8.173.1/24
!
interface 8786101219
 ip address 10.8.171.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
