!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node54
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 546697109
 ip address 10.8.108.1/24
!
interface 545597109
 ip address 10.8.107.1/24
!
interface 545397109
 ip address 10.8.105.2/24
!
interface 544297109
 ip address 10.8.84.2/24
!
ip forwarding
!
!
line vty
!
