!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node90
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 9091101587
 ip address 10.8.179.1/24
!
interface 9089101587
 ip address 10.8.177.2/24
!
interface 9078101587
 ip address 10.8.156.2/24
!
ip forwarding
!
!
line vty
!
