!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node69
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 697098985
 ip address 10.8.137.1/24
!
interface 696898985
 ip address 10.8.135.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
