!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node61
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 618497988
 ip address 10.8.122.1/24
!
interface 616297988
 ip address 10.8.121.1/24
!
interface 617297988
 ip address 10.8.143.2/24
!
interface 615097988
 ip address 10.8.100.2/24
!
ip forwarding
!
!
line vty
!
