!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node50
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 506196609
 ip address 10.8.100.1/24
!
interface 505196609
 ip address 10.8.99.1/24
!
interface 504996609
 ip address 10.8.97.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
