!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node91
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 9192101708
 ip address 10.8.181.1/24
!
interface 9190101708
 ip address 10.8.179.2/24
!
interface 9179101708
 ip address 10.8.158.2/24
!
ip forwarding
!
!
line vty
!
