!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node37
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 376095020
 ip address 10.8.74.1/24
!
interface 373895020
 ip address 10.8.73.1/24
!
interface 374895020
 ip address 10.8.95.2/24
!
interface 372695020
 ip address 10.8.52.2/24
!
ip forwarding
!
!
line vty
!
