!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node66_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 667898605
!
interface 666798605
!
interface 666598605
!
interface 665498605
!
router ospf
 ospf router-id 10.8.0.66
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
