!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node66
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 667898605
 ip address 10.8.132.1/24
!
interface 666798605
 ip address 10.8.131.1/24
!
interface 666598605
 ip address 10.8.129.2/24
!
interface 665498605
 ip address 10.8.108.2/24
!
ip forwarding
!
!
line vty
!
