!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node57
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 575897494
 ip address 10.8.113.1/24
!
interface 575697494
 ip address 10.8.111.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
