!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node42
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 425495622
 ip address 10.8.84.1/24
!
interface 424395622
 ip address 10.8.83.1/24
!
interface 424195622
 ip address 10.8.81.2/24
!
interface 423095622
 ip address 10.8.60.2/24
!
ip forwarding
!
!
line vty
!
