!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node29_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 294194016
!
interface 293094016
!
interface 292894016
!
interface 291794016
!
router ospf
 ospf router-id 10.8.0.29
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
