!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node29
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 294194016
 ip address 10.8.58.1/24
!
interface 293094016
 ip address 10.8.57.1/24
!
interface 292894016
 ip address 10.8.55.2/24
!
interface 291794016
 ip address 10.8.34.2/24
!
ip forwarding
!
!
line vty
!
