!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node89
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 8990101465
 ip address 10.8.177.1/24
!
interface 8988101465
 ip address 10.8.175.2/24
!
interface 8977101465
 ip address 10.8.154.2/24
!
ip forwarding
!
!
line vty
!
