!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node13
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 133692026
 ip address 10.8.26.1/24
!
interface 131492026
 ip address 10.8.25.1/24
!
interface 132492026
 ip address 10.8.47.2/24
!
interface 13292026
 ip address 10.8.4.2/24
!
ip forwarding
!
!
line vty
!
