!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node59
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 596097739
 ip address 10.8.117.1/24
!
interface 595897739
 ip address 10.8.115.2/24
!
interface 594897739
 ip address 10.8.96.2/24
!
ip forwarding
!
!
line vty
!
