!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname r1
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface v0102
 ip address 10.9.1.1/24
!
interface v0107
 ip address 10.9.3.1/24
!
interface v0109
 ip address 10.9.2.1/24
!
interface v1111
 ip address 10.9.4.1/24
!
ip forwarding
!
!
line vty
!
