!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node51
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 515296738
 ip address 10.8.101.1/24
!
interface 515096738
 ip address 10.8.99.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
