!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node33
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 333494519
 ip address 10.8.65.1/24
!
interface 333294519
 ip address 10.8.63.2/24
!
interface 332194519
 ip address 10.8.42.2/24
!
ip forwarding
!
!
line vty
!
