!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node52
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 525396858
 ip address 10.8.103.1/24
!
interface 525196858
 ip address 10.8.101.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
