!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node56
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 566897367
 ip address 10.8.112.1/24
!
interface 565797367
 ip address 10.8.111.1/24
!
interface 565597367
 ip address 10.8.109.2/24
!
interface 564497367
 ip address 10.8.88.2/24
!
ip forwarding
!
!
line vty
!
