!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node70
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 707199111
 ip address 10.8.139.1/24
!
interface 706999111
 ip address 10.8.137.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
