!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node77
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 778999980
 ip address 10.8.154.1/24
!
interface 777899980
 ip address 10.8.153.1/24
!
interface 777699980
 ip address 10.8.151.2/24
!
interface 776599980
 ip address 10.8.130.2/24
!
ip forwarding
!
!
line vty
!
