!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node31
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 314394267
 ip address 10.8.62.1/24
!
interface 313294267
 ip address 10.8.61.1/24
!
interface 313094267
 ip address 10.8.59.2/24
!
interface 311994267
 ip address 10.8.38.2/24
!
ip forwarding
!
!
line vty
!
