!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node62
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 627398118
 ip address 10.8.124.1/24
!
interface 626398118
 ip address 10.8.123.1/24
!
interface 626198118
 ip address 10.8.121.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
