!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node53_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 536596984
!
interface 535496984
!
interface 535296984
!
interface 534196984
!
router ospf
 ospf router-id 10.8.0.53
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
