!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node40
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 404195391
 ip address 10.8.79.1/24
!
interface 403995391
 ip address 10.8.77.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
