!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node25_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 254893516
!
interface 252693516
!
interface 253693516
!
interface 251493516
!
router ospf
 ospf router-id 10.8.0.25
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
