!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node25
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 254893516
 ip address 10.8.50.1/24
!
interface 252693516
 ip address 10.8.49.1/24
!
interface 253693516
 ip address 10.8.71.2/24
!
interface 251493516
 ip address 10.8.28.2/24
!
ip forwarding
!
!
line vty
!
