!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node84_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 8495100842
!
interface 8473100842
!
interface 8483100842
!
interface 8461100842
!
router ospf
 ospf router-id 10.8.0.84
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
