!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node84
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 8495100842
 ip address 10.8.168.1/24
!
interface 8473100842
 ip address 10.8.167.1/24
!
interface 8483100842
 ip address 10.8.165.2/24
!
interface 8461100842
 ip address 10.8.122.2/24
!
ip forwarding
!
!
line vty
!
