!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node48_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 485996356
!
interface 483796356
!
interface 484796356
!
interface 482596356
!
router ospf
 ospf router-id 10.8.0.48
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
