!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node41_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 415395508
!
interface 414295508
!
interface 414095508
!
interface 412995508
!
router ospf
 ospf router-id 10.8.0.41
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
