!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node46
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 464796106
 ip address 10.8.91.1/24
!
interface 464596106
 ip address 10.8.89.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
