!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node60
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 607197860
 ip address 10.8.120.1/24
!
interface 604997860
 ip address 10.8.119.1/24
!
interface 605997860
 ip address 10.8.117.2/24
!
interface 603797860
 ip address 10.8.74.2/24
!
ip forwarding
!
!
line vty
!
