!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node82
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 8283100586
 ip address 10.8.163.1/24
!
interface 8281100586
 ip address 10.8.161.2/24
!
interface 8271100586
 ip address 10.8.142.2/24
!
ip forwarding
!
!
line vty
!
