!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node9
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 92191534
 ip address 10.8.18.1/24
!
interface 91091534
 ip address 10.8.17.1/24
!
interface 9891534
 ip address 10.8.15.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
