!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node14
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 142592148
 ip address 10.8.28.1/24
!
interface 141592148
 ip address 10.8.27.1/24
!
interface 141392148
 ip address 10.8.25.2/24
!
interface 14392148
 ip address 10.8.6.2/24
!
ip forwarding
!
!
line vty
!
