!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node55
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 556797233
 ip address 10.8.110.1/24
!
interface 555697233
 ip address 10.8.109.1/24
!
interface 555497233
 ip address 10.8.107.2/24
!
interface 554397233
 ip address 10.8.86.2/24
!
ip forwarding
!
!
line vty
!
