!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node43
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 435595735
 ip address 10.8.86.1/24
!
interface 434495735
 ip address 10.8.85.1/24
!
interface 434295735
 ip address 10.8.83.2/24
!
interface 433195735
 ip address 10.8.62.2/24
!
ip forwarding
!
!
line vty
!
