!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node58
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 585997613
 ip address 10.8.115.1/24
!
interface 585797613
 ip address 10.8.113.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
