!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node12
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 122391900
 ip address 10.8.24.1/24
!
interface 12191900
 ip address 10.8.23.1/24
!
interface 121191900
 ip address 10.8.21.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
