!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node47
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 474896229
 ip address 10.8.93.1/24
!
interface 474696229
 ip address 10.8.91.2/24
!
interface 473696229
 ip address 10.8.72.2/24
!
ip forwarding
!
!
line vty
!
