!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node94
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 9495102075
 ip address 10.8.187.1/24
!
interface 9493102075
 ip address 10.8.185.2/24
!
interface 9483102075
 ip address 10.8.166.2/24
!
ip forwarding
!
!
line vty
!
