!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node93_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
!
!
interface 9394101957
!
interface 9392101957
!
!
!
router ospf
 ospf router-id 10.8.0.93
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
