!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node93
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 9394101957
 ip address 10.8.185.1/24
!
interface 9392101957
 ip address 10.8.183.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
