!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node26
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 263793644
 ip address 10.8.52.1/24
!
interface 262793644
 ip address 10.8.51.1/24
!
interface 262593644
 ip address 10.8.49.2/24
!
interface 261593644
 ip address 10.8.30.2/24
!
ip forwarding
!
!
line vty
!
