!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node92
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 9293101830
 ip address 10.8.183.1/24
!
interface 9291101830
 ip address 10.8.181.2/24
!
interface 9280101830
 ip address 10.8.160.2/24
!
ip forwarding
!
!
line vty
!
