!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node2
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 21390677
 ip address 10.8.4.1/24
!
interface 2390677
 ip address 10.8.3.1/24
!
interface 2190677
 ip address 10.8.1.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
