!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node10
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 101191656
 ip address 10.8.19.1/24
!
interface 10991656
 ip address 10.8.17.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
