!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node88
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 8889101344
 ip address 10.8.175.1/24
!
interface 8887101344
 ip address 10.8.173.2/24
!
interface 8876101344
 ip address 10.8.152.2/24
!
ip forwarding
!
!
line vty
!
