!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node8
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 82091412
 ip address 10.8.16.1/24
!
interface 8991412
 ip address 10.8.15.1/24
!
interface 8791412
 ip address 10.8.13.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
