!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node86
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
!
!
!
interface 8687101096
 ip address 10.8.171.1/24
!
interface 8685101096
 ip address 10.8.169.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
