!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node30_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 304294143
!
interface 303194143
!
interface 302994143
!
interface 301894143
!
router ospf
 ospf router-id 10.8.0.30
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
