!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node30
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 304294143
 ip address 10.8.60.1/24
!
interface 303194143
 ip address 10.8.59.1/24
!
interface 302994143
 ip address 10.8.57.2/24
!
interface 301894143
 ip address 10.8.36.2/24
!
ip forwarding
!
!
line vty
!
