!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node36
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 364794900
 ip address 10.8.72.1/24
!
interface 362594900
 ip address 10.8.71.1/24
!
interface 363594900
 ip address 10.8.69.2/24
!
interface 361394900
 ip address 10.8.26.2/24
!
ip forwarding
!
!
line vty
!
