!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node49_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 497296481
!
interface 495096481
!
interface 496096481
!
interface 493896481
!
router ospf
 ospf router-id 10.8.0.49
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
