!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node49
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 497296481
 ip address 10.8.98.1/24
!
interface 495096481
 ip address 10.8.97.1/24
!
interface 496096481
 ip address 10.8.119.2/24
!
interface 493896481
 ip address 10.8.76.2/24
!
ip forwarding
!
!
line vty
!
