!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node7_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 71991289
!
interface 7891289
!
interface 7691289
!
!
!
router ospf
 ospf router-id 10.8.0.7
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
