!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node7
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 71991289
 ip address 10.8.14.1/24
!
interface 7891289
 ip address 10.8.13.1/24
!
interface 7691289
 ip address 10.8.11.2/24
!
!
!
!
ip forwarding
!
!
line vty
!
