!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node21
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 213393021
 ip address 10.8.42.1/24
!
interface 212293021
 ip address 10.8.41.1/24
!
interface 212093021
 ip address 10.8.39.2/24
!
interface 21993021
 ip address 10.8.18.2/24
!
ip forwarding
!
!
line vty
!
