!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node24_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 243593387
!
interface 241393387
!
interface 242393387
!
interface 24193387
!
router ospf
 ospf router-id 10.8.0.24
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
