!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node1_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 12490545
!
interface 1290545
!
interface 11290545
!
!
!
router ospf
 ospf router-id 10.8.0.1
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
