!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node71_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 718299241
!
interface 717299241
!
interface 717099241
!
interface 716099241
!
router ospf
 ospf router-id 10.8.0.71
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
