!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node76_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 768899858
!
interface 767799858
!
interface 767599858
!
interface v1111
!
router ospf
 ospf router-id 10.8.0.76
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
