!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node76
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 768899858
 ip address 10.8.152.1/24
!
interface 767799858
 ip address 10.8.151.1/24
!
interface 767599858
 ip address 10.8.149.2/24
!
interface v1111
 ip address 10.9.4.1/24
!
ip forwarding
!
!
line vty
!
