!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node35_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
!
!
interface 353694773
!
interface 353494773
!
interface 352494773
!
router ospf
 ospf router-id 10.8.0.35
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
