!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node78
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 7890100084
 ip address 10.8.156.1/24
!
interface 7879100084
 ip address 10.8.155.1/24
!
interface 7877100084
 ip address 10.8.153.2/24
!
interface 7866100084
 ip address 10.8.132.2/24
!
ip forwarding
!
!
line vty
!
