!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node67_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 677998727
!
interface 676898727
!
interface 676698727
!
interface 675598727
!
router ospf
 ospf router-id 10.8.0.67
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
