!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node67
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 677998727
 ip address 10.8.134.1/24
!
interface 676898727
 ip address 10.8.133.1/24
!
interface 676698727
 ip address 10.8.131.2/24
!
interface 675598727
 ip address 10.8.110.2/24
!
ip forwarding
!
!
line vty
!
