!
! Zebra configuration saved from vty
!   2021/03/24 14:51:44
!
hostname node83
password zebra
enable password zebra
!
interface eth0
!
interface lo
!
interface 8394100718
 ip address 10.8.166.1/24
!
interface 8384100718
 ip address 10.8.165.1/24
!
interface 8382100718
 ip address 10.8.163.2/24
!
interface 8372100718
 ip address 10.8.144.2/24
!
ip forwarding
!
!
line vty
!
