!
! Zebra configuration saved from vty
!   2021/03/24 14:54:55
!
hostname node38_ospf
password zebra
log file /usr/local/etc/ospfd.log
log stdout
!
debug ospf event
!
!
interface eth0
!
interface lo
!
interface 384995146
!
interface 383995146
!
interface 383795146
!
interface 382795146
!
router ospf
 ospf router-id 10.8.0.38
 network 10.8.0.0/16 area 0.0.0.0
!
line vty
!
